import type { EngineContext } from "../core/context.js";
import { assembledValue, childrenOf, decodeGedcom, parseGedcom, type GedcomLine } from "../core/gedcom.js";

const EVENT_TAGS=new Set(["BIRT","CHR","BAPM","RESI","CENS","MARR","DIV","DEAT","BURI","IMMI","EMIG","MILI","OCCU","PROB","WILL","EVEN"]);
const CLEAR_TABLES=["scored_candidates","suppression_log","candidate_pairs","presence_intervals","kinship_distance","kinship_edges","event_dates","events","family_children","families","individuals","raw_records"] as const;
interface Root{readonly root:GedcomLine;readonly children:ReadonlyArray<GedcomLine>}
const child=(lines:ReadonlyArray<GedcomLine>,parent:number,tag:string):GedcomLine|undefined=>childrenOf(lines,parent).find(line=>line.tag===tag);
const xref=(value:string):string|null=>/^@[^@\s]+@$/.exec(value.trim())?.[0]??null;
function id(value:number|bigint):number{const result=Number(value);if(!Number.isSafeInteger(result))throw new Error("SQLite row id exceeds safe integer range");return result}
const roots=(lines:ReadonlyArray<GedcomLine>,tag:string):ReadonlyArray<Root>=>lines.filter(line=>line.level===0&&line.tag===tag).map(root=>({root,children:childrenOf(lines,root.index)}));
function name(lines:ReadonlyArray<GedcomLine>,record:Root):{given:string|null;surname:string|null;full:string|null}{const line=record.children.find(item=>item.tag==="NAME");if(line===undefined)return{given:null,surname:null,full:null};const full=assembledValue(lines,line).trim()||null,givenLine=child(lines,line.index,"GIVN"),surnameLine=child(lines,line.index,"SURN"),slash=full===null?null:/^(.*?)\s*\/([^/]*)\//.exec(full);return{given:givenLine===undefined?(slash?.[1]?.trim()||null):(assembledValue(lines,givenLine).trim()||null),surname:surnameLine===undefined?(slash?.[2]?.trim()||null):(assembledValue(lines,surnameLine).trim()||null),full}}
function parts(lines:ReadonlyArray<GedcomLine>,line:GedcomLine):{type:string;date:string|null;place:string|null;sources:number;note:string|null}{const direct=childrenOf(lines,line.index),date=direct.find(item=>item.tag==="DATE"),place=direct.find(item=>item.tag==="PLAC"),note=direct.find(item=>item.tag==="NOTE"),type=direct.find(item=>item.tag==="TYPE");return{type:line.tag==="EVEN"&&type!==undefined?(assembledValue(lines,type).trim()||"EVEN"):line.tag,date:date===undefined?null:(assembledValue(lines,date).trim()||null),place:place===undefined?null:(assembledValue(lines,place).trim()||null),sources:direct.filter(item=>item.tag==="SOUR").length,note:note===undefined?null:(assembledValue(lines,note).trim()||null)}}
function rawBirthYear(record:Root,lines:ReadonlyArray<GedcomLine>):number|null{const birth=record.children.find(line=>line.tag==="BIRT"),date=birth===undefined?undefined:child(lines,birth.index,"DATE"),match=date===undefined?null:/(\d{3,4})(?:\/\d{2,4})?/.exec(date.value);return match===null?null:Number(match[1])}
function linkType(lines:ReadonlyArray<GedcomLine>,familyXref:string,childXref:string,people:ReadonlyArray<Root>):string{const person=people.find(entry=>entry.root.xref===childXref),famc=person?.children.find(line=>line.tag==="FAMC"&&xref(line.value)===familyXref),pedi=famc===undefined?undefined:child(lines,famc.index,"PEDI")?.value.trim().toLowerCase();if(pedi==="adopted"||pedi==="adop")return"adopted";if(pedi==="foster")return"foster";if(pedi==="sealed"||pedi==="sealing")return"sealed";return"birth"}

export async function run(ctx:EngineContext):Promise<void>{
  if(ctx.inputPath===undefined)throw new Error("ingest requires --gedcom <path>");
  ctx.progress.passStarted("ingest");
  const decoded=decodeGedcom(await ctx.fileSource.readGedcom(ctx.inputPath)),parsed=parseGedcom(decoded.text),people=roots(parsed.lines,"INDI"),families=roots(parsed.lines,"FAM"),personIds=new Map<string,number>(),familyIds=new Map<string,number>(),rawIds=new Map<number,number>();let eventCount=0;
  ctx.storage.transaction(():void=>{
    for(const table of CLEAR_TABLES)ctx.storage.run(`DELETE FROM ${table}`);
    let recordXref="";
    for(const line of parsed.lines){if(line.level===0)recordXref=line.xref??"";const result=ctx.storage.run("INSERT INTO raw_records(gedcom_xref,tag,level,value,parent_id,line_no) VALUES(?,?,?,?,?,?)",[recordXref,line.tag,line.level,line.value,line.parentIndex===null?null:(rawIds.get(line.parentIndex)??null),line.lineNo]);rawIds.set(line.index,id(result.lastInsertRowid))}
    for(const person of people){if(person.root.xref===null)continue;const parsedName=name(parsed.lines,person),sex=person.children.find(line=>line.tag==="SEX")?.value.trim()||null,hasDeath=person.children.some(line=>line.tag==="DEAT"||line.tag==="BURI"),year=rawBirthYear(person,parsed.lines),living=!hasDeath&&(year===null||year>ctx.config.privacy.living_cutoff_year),result=ctx.storage.run("INSERT INTO individuals(gedcom_xref,name_given,name_surname,name_full,sex,is_living,lifespan_src) VALUES(?,?,?,?,?,?,?)",[person.root.xref,parsedName.given,parsedName.surname,parsedName.full,sex,living?1:0,"unknown"]);personIds.set(person.root.xref,id(result.lastInsertRowid))}
    for(const family of families){if(family.root.xref===null)continue;const husband=xref(family.children.find(line=>line.tag==="HUSB")?.value??""),wife=xref(family.children.find(line=>line.tag==="WIFE")?.value??""),result=ctx.storage.run("INSERT INTO families(gedcom_xref,husband_id,wife_id) VALUES(?,?,?)",[family.root.xref,husband===null?null:(personIds.get(husband)??null),wife===null?null:(personIds.get(wife)??null)]);familyIds.set(family.root.xref,id(result.lastInsertRowid))}
    for(const family of families){if(family.root.xref===null)continue;const familyId=familyIds.get(family.root.xref);if(familyId===undefined)continue;for(const line of family.children.filter(item=>item.tag==="CHIL")){const childXref=xref(line.value),childId=childXref===null?undefined:personIds.get(childXref);if(childXref!==null&&childId!==undefined)ctx.storage.run("INSERT INTO family_children(family_id,child_id,link_type) VALUES(?,?,?)",[familyId,childId,linkType(parsed.lines,family.root.xref,childXref,people)])}}
    const eventRows:Array<{subjectType:"individual"|"family";subjectId:number;line:GedcomLine}>=[];for(const person of people){const subjectId=person.root.xref===null?undefined:personIds.get(person.root.xref);if(subjectId!==undefined)for(const line of person.children.filter(item=>EVENT_TAGS.has(item.tag)))eventRows.push({subjectType:"individual",subjectId,line})}for(const family of families){const subjectId=family.root.xref===null?undefined:familyIds.get(family.root.xref);if(subjectId!==undefined)for(const line of family.children.filter(item=>EVENT_TAGS.has(item.tag)))eventRows.push({subjectType:"family",subjectId,line})}eventRows.sort((a,b)=>a.line.lineNo-b.line.lineNo);for(const event of eventRows){const data=parts(parsed.lines,event.line);ctx.storage.run("INSERT INTO events(subject_type,subject_id,event_type,date_raw,place_raw,source_count,note,line_no) VALUES(?,?,?,?,?,?,?,?)",[event.subjectType,event.subjectId,data.type,data.date,data.place,data.sources,data.note,event.line.lineNo]);eventCount++}
    ctx.storage.run("INSERT INTO meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",["input_encoding",decoded.encoding]);ctx.storage.run("INSERT INTO meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",["input_unmappable_bytes",String(decoded.unmappableBytes)]);
  });
  const withEvents=new Set(ctx.storage.all<{readonly subject_id:number}>("SELECT DISTINCT subject_id FROM events WHERE subject_type=? ORDER BY subject_id",["individual"]).map(row=>row.subject_id)),without=[...personIds.entries()].filter(([,personId])=>!withEvents.has(personId)).map(([personXref])=>personXref).sort();if(parsed.unparsed.length>0)ctx.progress.warn(`${parsed.unparsed.length} GEDCOM lines were structurally unparsed`);ctx.progress.passFinished("ingest",{encoding:decoded.encoding,unmappableBytes:decoded.unmappableBytes,countsByTag:parsed.countsByTag,unparsedLines:parsed.unparsed.length,individuals:people.length,families:families.length,events:eventCount,individualsWithNoEvents:without});
}
