import type { EngineContext } from "../core/context.js";
import { clampToLifespan, projectWindow, projectionFor, type LifespanWindow } from "../core/presence.js";

interface EventRow extends Readonly<Record<string, unknown>> { readonly id: number; readonly subject_type: string; readonly subject_id: number; readonly event_type: string; readonly place_raw: string | null; readonly date_start: string | null; readonly date_end: string | null }
interface PlaceRow extends Readonly<Record<string, unknown>> { readonly id: number; readonly place_raw: string; readonly lat: number | null; readonly lon: number | null; readonly radius_km: number | null; readonly precision_tier: string | null }
interface PersonRow extends Readonly<Record<string, unknown>> { readonly id: number; readonly birth_start: string | null; readonly death_end: string | null }
interface FamilyRow extends Readonly<Record<string, unknown>> { readonly id: number; readonly husband_id: number | null; readonly wife_id: number | null }
interface ChildRow extends Readonly<Record<string, unknown>> { readonly family_id: number; readonly child_id: number }
interface ParentLinks { readonly mothers: ReadonlyArray<number>; readonly fathers: ReadonlyArray<number>; readonly all: ReadonlyArray<number> }
interface PresenceDraft { readonly individualId: number; readonly eventId: number; readonly placeId: number; readonly dateStart: string; readonly dateEnd: string; readonly role: string; readonly confidence: number; readonly precisionTier: string; readonly radiusKm: number }
function add(map: Map<string, PresenceDraft>, draft: PresenceDraft): void { const key = `${draft.individualId}:${draft.role}`; const previous = map.get(key); if (previous === undefined || previous.confidence < draft.confidence) map.set(key, draft); }
function addRelation(map: Map<number, number[]>, a: number, b: number): void { const values = map.get(a) ?? []; if (!values.includes(b)) values.push(b); map.set(a, values); }
function elapsed(start: string, end: string): number { return Math.max(0, Date.parse(end) - Date.parse(start)); }
export async function run(ctx: EngineContext): Promise<void> {
  const pass = "presence", started = ctx.env.now(); ctx.progress.passStarted(pass);
  const events = ctx.storage.all<EventRow>(`SELECT e.id,e.subject_type,e.subject_id,e.event_type,e.place_raw,d.date_start,d.date_end FROM events e LEFT JOIN event_dates d ON d.event_id=e.id ORDER BY e.id`);
  const places = new Map(ctx.storage.all<PlaceRow>("SELECT id,place_raw,lat,lon,radius_km,precision_tier FROM places ORDER BY id").map((row) => [row.place_raw, row]));
  const lifespans = new Map(ctx.storage.all<PersonRow>("SELECT id,birth_start,death_end FROM individuals ORDER BY id").map((row) => [row.id, { birthStart: row.birth_start, deathEnd: row.death_end } satisfies LifespanWindow]));
  const families = ctx.storage.all<FamilyRow>("SELECT id,husband_id,wife_id FROM families ORDER BY id"), children = ctx.storage.all<ChildRow>("SELECT family_id,child_id FROM family_children ORDER BY family_id,child_id"), familyById = new Map(families.map((row) => [row.id, row])), spouses = new Map<number, number[]>(), parentDraft = new Map<number, { mothers: number[]; fathers: number[]; all: number[] }>();
  for (const family of families) if (family.husband_id !== null && family.wife_id !== null) { addRelation(spouses, family.husband_id, family.wife_id); addRelation(spouses, family.wife_id, family.husband_id); }
  for (const child of children) { const family = familyById.get(child.family_id); if (family === undefined) continue; const links = parentDraft.get(child.child_id) ?? { mothers: [], fathers: [], all: [] }; if (family.wife_id !== null) { if (!links.mothers.includes(family.wife_id)) links.mothers.push(family.wife_id); if (!links.all.includes(family.wife_id)) links.all.push(family.wife_id); } if (family.husband_id !== null) { if (!links.fathers.includes(family.husband_id)) links.fathers.push(family.husband_id); if (!links.all.includes(family.husband_id)) links.all.push(family.husband_id); } parentDraft.set(child.child_id, links); }
  const parents = parentDraft as ReadonlyMap<number, ParentLinks>, drafts: PresenceDraft[] = [];
  let unsupportedEvents = 0, unparsedDates = 0, unresolvedPlaces = 0, outsideLifespan = 0;
  for (const [index, event] of events.entries()) {
    const projection = projectionFor(event.event_type, ctx.config.presence.projections); if (projection === null) { unsupportedEvents += 1; ctx.progress.progress(pass, index + 1, events.length); continue; }
    if (event.date_start === null || event.date_end === null) { unparsedDates += 1; ctx.progress.progress(pass, index + 1, events.length); continue; }
    const place = event.place_raw === null ? undefined : places.get(event.place_raw); if (place === undefined || place.lat === null || place.lon === null || place.radius_km === null || place.precision_tier === null || place.precision_tier === "unknown") { unresolvedPlaces += 1; ctx.progress.progress(pass, index + 1, events.length); continue; }
    const baseWindow = projectWindow(event.date_start, event.date_end, event.event_type, ctx.config.presence.point_event_dwell_days, ctx.config.presence.transit_event_window_days), eventDrafts = new Map<string, PresenceDraft>();
    const addPerson = (individualId: number, role: string, confidence: number): void => { const boundedInterval = clampToLifespan(baseWindow, lifespans.get(individualId) ?? { birthStart: null, deathEnd: null }); if (boundedInterval === null) { outsideLifespan += 1; return; } add(eventDrafts, { individualId, eventId: event.id, placeId: place.id, dateStart: boundedInterval.start, dateEnd: boundedInterval.end, role, confidence, precisionTier: place.precision_tier ?? "unknown", radiusKm: place.radius_km ?? 0 }); };
    const addParents = (personId: number, confidence: number): void => { for (const id of parents.get(personId)?.all ?? []) addPerson(id, "parent", confidence); };
    if (event.subject_type === "individual") { addPerson(event.subject_id, "subject", projection.subject); if (projection.spouse !== undefined) for (const id of spouses.get(event.subject_id) ?? []) addPerson(id, "spouse", projection.spouse); const links = parents.get(event.subject_id); if (projection.mother !== undefined) for (const id of links?.mothers ?? []) addPerson(id, "parent", projection.mother); if (projection.father !== undefined) for (const id of links?.fathers ?? []) addPerson(id, "parent", projection.father); if (projection.parents !== undefined) addParents(event.subject_id, projection.parents); }
    else if (event.subject_type === "family") { const family = familyById.get(event.subject_id), participants = [family?.husband_id ?? null, family?.wife_id ?? null].filter((id): id is number => id !== null); for (const id of participants) addPerson(id, "subject", projection.subject); if (projection.parents !== undefined) for (const id of participants) addParents(id, projection.parents); }
    drafts.push(...[...eventDrafts.values()].sort((a, b) => a.individualId - b.individualId || (a.role < b.role ? -1 : a.role > b.role ? 1 : 0))); ctx.progress.progress(pass, index + 1, events.length);
  }
  ctx.storage.transaction((): void => { ctx.storage.run("DELETE FROM scored_candidates"); ctx.storage.run("DELETE FROM suppression_log"); ctx.storage.run("DELETE FROM candidate_pairs"); ctx.storage.run("DELETE FROM presence_intervals"); for (const row of drafts) ctx.storage.run("INSERT INTO presence_intervals(individual_id,event_id,place_id,date_start,date_end,role,presence_conf,precision_tier,radius_km) VALUES(?,?,?,?,?,?,?,?,?)", [row.individualId, row.eventId, row.placeId, row.dateStart, row.dateEnd, row.role, row.confidence, row.precisionTier, row.radiusKm]); });
  ctx.progress.passFinished(pass, { rows_in: events.length, rows_out: drafts.length, excluded_unsupported_event: unsupportedEvents, excluded_unparsed_date: unparsedDates, excluded_unresolved_place: unresolvedPlaces, excluded_outside_lifespan: outsideLifespan, elapsed_ms: elapsed(started, ctx.env.now()) });
}
