import type { EngineContext } from "../core/context.js";
import { relationshipSummary } from "../core/kinship.js";
import { firstSuppression, scoreCandidate, type DatePrecision, type PrecisionTier, type ScoreComponents } from "../core/scoring.js";
import { createKinshipService } from "./kinship.js";
interface CandidateRow extends Readonly<Record<string, unknown>> { readonly candidate_id: number; readonly a_id: number; readonly b_id: number; readonly overlap_start: string; readonly overlap_end: string; readonly overlap_days: number; readonly distance_km: number; readonly combined_radius: number; readonly a_event_id: number; readonly b_event_id: number; readonly a_presence_conf: number; readonly b_presence_conf: number; readonly a_tier: string; readonly b_tier: string; readonly a_geocode_conf: number | null; readonly b_geocode_conf: number | null; readonly a_event_type: string; readonly b_event_type: string; readonly a_date_raw: string | null; readonly b_date_raw: string | null; readonly a_place_raw: string | null; readonly b_place_raw: string | null; readonly a_place_label: string | null; readonly b_place_label: string | null; readonly a_date_precision: string; readonly b_date_precision: string; readonly a_line_no: number | null; readonly b_line_no: number | null; readonly a_place_id: number; readonly b_place_id: number; readonly a_name: string | null; readonly b_name: string | null; readonly a_living: number; readonly b_living: number }
interface ScoredDraft { readonly candidateId: number; readonly components: ScoreComponents; readonly explanation: string }
interface LogDraft { readonly aId: number; readonly bId: number; readonly reason: string; readonly detail: string }
const TIERS: readonly PrecisionTier[] = ["address", "locality", "district", "region", "country", "unknown"];
const DATE_PRECISIONS: readonly DatePrecision[] = ["day", "month", "year", "decade", "range", "inferred"];
function tier(value: string): PrecisionTier { return TIERS.includes(value as PrecisionTier) ? value as PrecisionTier : "unknown"; }
function datePrecision(value: string): DatePrecision { return DATE_PRECISIONS.includes(value as DatePrecision) ? value as DatePrecision : "inferred"; }
function coarser(value: PrecisionTier, minimum: string): boolean { return TIERS.indexOf(value) > TIERS.indexOf(tier(minimum)); }
function elapsed(start: string, end: string): number { return Math.max(0, Date.parse(end) - Date.parse(start)); }
function increment(counts: Map<string, number>, reason: string): void { counts.set(reason, (counts.get(reason) ?? 0) + 1); }
function explanation(row: CandidateRow, relationship: string): string { const label = row.a_place_label ?? row.b_place_label ?? row.a_place_raw ?? row.b_place_raw ?? "the recorded place", confidence = Math.sqrt(row.a_presence_conf * row.b_presence_conf).toFixed(2), placeTier = coarser(tier(row.a_tier), row.b_tier) ? row.a_tier : row.b_tier; return `${row.a_name ?? `Individual ${row.a_id}`} and ${row.b_name ?? `Individual ${row.b_id}`} were likely within ${row.distance_km.toFixed(1)} km of each other near ${label} between ${row.overlap_start} and ${row.overlap_end}. Relationship: ${relationship}. Evidence: ${row.a_event_type} (${row.a_date_raw ?? "date unavailable"}, ${row.a_place_raw ?? "place unavailable"}) and ${row.b_event_type} (${row.b_date_raw ?? "date unavailable"}, ${row.b_place_raw ?? "place unavailable"}). Confidence: place ${placeTier}, presence ${confidence}.`; }
export async function run(ctx: EngineContext): Promise<void> {
  const pass = "score", started = ctx.env.now(); ctx.progress.passStarted(pass);
  const rows = ctx.storage.all<CandidateRow>(`SELECT c.id AS candidate_id,c.a_id,c.b_id,c.overlap_start,c.overlap_end,c.overlap_days,c.distance_km,c.combined_radius,pa.event_id AS a_event_id,pb.event_id AS b_event_id,pa.presence_conf AS a_presence_conf,pb.presence_conf AS b_presence_conf,pa.precision_tier AS a_tier,pb.precision_tier AS b_tier,pla.geocode_conf AS a_geocode_conf,plb.geocode_conf AS b_geocode_conf,ea.event_type AS a_event_type,eb.event_type AS b_event_type,ea.date_raw AS a_date_raw,eb.date_raw AS b_date_raw,ea.place_raw AS a_place_raw,eb.place_raw AS b_place_raw,pla.place_normalized AS a_place_label,plb.place_normalized AS b_place_label,COALESCE(eda.precision,'inferred') AS a_date_precision,COALESCE(edb.precision,'inferred') AS b_date_precision,ea.line_no AS a_line_no,eb.line_no AS b_line_no,pa.place_id AS a_place_id,pb.place_id AS b_place_id,ia.name_full AS a_name,ib.name_full AS b_name,ia.is_living AS a_living,ib.is_living AS b_living FROM candidate_pairs c JOIN presence_intervals pa ON pa.id=c.a_interval_id JOIN presence_intervals pb ON pb.id=c.b_interval_id JOIN events ea ON ea.id=pa.event_id JOIN events eb ON eb.id=pb.event_id LEFT JOIN event_dates eda ON eda.event_id=ea.id LEFT JOIN event_dates edb ON edb.event_id=eb.id JOIN places pla ON pla.id=pa.place_id JOIN places plb ON plb.id=pb.place_id JOIN individuals ia ON ia.id=c.a_id JOIN individuals ib ON ib.id=c.b_id ORDER BY c.id`), spouses = new Set(ctx.storage.all<{ readonly from_id: number; readonly to_id: number }>("SELECT from_id,to_id FROM kinship_edges WHERE edge_type='spouse' ORDER BY from_id,to_id").map((edge) => `${edge.from_id}:${edge.to_id}`)), kinship = createKinshipService(ctx), scored: ScoredDraft[] = [], logs: LogDraft[] = [], reasons = new Map<string, number>();
  for (const [index, row] of rows.entries()) {
    const analysis = kinship.resolve(row.a_id, row.b_id), sameRecord = row.a_event_id === row.b_event_id || (row.a_line_no !== null && row.a_line_no === row.b_line_no), sameHousehold = row.a_event_id === row.b_event_id || (row.a_event_type === "CENS" && row.b_event_type === "CENS" && sameRecord && row.a_place_id === row.b_place_id), suppression = firstSuppression({ sameIndividual: row.a_id === row.b_id, sameHousehold, directSpouse: spouses.has(`${row.a_id}:${row.b_id}`) || spouses.has(`${row.b_id}:${row.a_id}`), bloodDegree: analysis.bloodDegree, graphDegree: analysis.graphDegree, sharedMrcaWithinCutoff: analysis.mrcaId !== null && analysis.aGenerationsToMrca !== null && analysis.bGenerationsToMrca !== null && analysis.aGenerationsToMrca <= ctx.config.kinship.generations_cutoff && analysis.bGenerationsToMrca <= ctx.config.kinship.generations_cutoff, sameBranch: analysis.sameBranch, branchDegree: analysis.bloodDegree ?? analysis.graphDegree, coarsePlace: coarser(tier(row.a_tier), ctx.config.place.min_tier) || coarser(tier(row.b_tier), ctx.config.place.min_tier), lowConfidence: row.a_presence_conf < ctx.config.presence.min_presence_conf || row.b_presence_conf < ctx.config.presence.min_presence_conf || (row.a_geocode_conf ?? 0) < ctx.config.place.min_geocode_conf || (row.b_geocode_conf ?? 0) < ctx.config.place.min_geocode_conf, living: row.a_living !== 0 || row.b_living !== 0 }, { closeKinCutoff: ctx.config.kinship.close_kin_cutoff, inLawCutoff: ctx.config.kinship.in_law_cutoff, branchCutoff: ctx.config.kinship.branch_cutoff, includeLiving: ctx.config.privacy.include_living });
    if (suppression !== null) { logs.push({ aId: row.a_id, bId: row.b_id, reason: suppression, detail: `candidate=${row.candidate_id}` }); increment(reasons, suppression); ctx.progress.progress(pass, index + 1, rows.length); continue; }
    const components = scoreCandidate({ distanceKm: row.distance_km, combinedRadiusKm: row.combined_radius, proximityMultiplier: ctx.config.place.proximity_radius_multiplier, overlapDays: row.overlap_days, aDatePrecision: datePrecision(row.a_date_precision), bDatePrecision: datePrecision(row.b_date_precision), aTier: tier(row.a_tier), bTier: tier(row.b_tier), aPresenceConfidence: row.a_presence_conf, bPresenceConfidence: row.b_presence_conf, aGeocodeConfidence: row.a_geocode_conf ?? 0, bGeocodeConfidence: row.b_geocode_conf ?? 0, bloodDegree: analysis.bloodDegree, branchCutoff: ctx.config.kinship.branch_cutoff, sameSourceRecord: sameRecord }, ctx.config.scoring);
    if (components.score < ctx.config.scoring.score_threshold) { logs.push({ aId: row.a_id, bId: row.b_id, reason: "below_threshold", detail: `candidate=${row.candidate_id};score=${components.score.toFixed(6)}` }); increment(reasons, "below_threshold"); } else scored.push({ candidateId: row.candidate_id, components, explanation: explanation(row, relationshipSummary(analysis)) });
    ctx.progress.progress(pass, index + 1, rows.length);
  }
  scored.sort((a, b) => b.components.score - a.components.score || a.candidateId - b.candidateId); const kept = scored.slice(0, ctx.config.scoring.max_candidates); for (const row of scored.slice(ctx.config.scoring.max_candidates)) { const candidate = rows.find((item) => item.candidate_id === row.candidateId); if (candidate !== undefined) logs.push({ aId: candidate.a_id, bId: candidate.b_id, reason: "below_limit", detail: `candidate=${row.candidateId}` }); increment(reasons, "below_limit"); }
  ctx.storage.transaction((): void => { ctx.storage.run("DELETE FROM scored_candidates"); ctx.storage.run("DELETE FROM suppression_log"); for (const row of logs) ctx.storage.run("INSERT INTO suppression_log(a_id,b_id,reason,detail) VALUES(?,?,?,?)", [row.aId, row.bId, row.reason, row.detail]); for (const row of kept) ctx.storage.run("INSERT INTO scored_candidates(candidate_id,score,s_proximity,s_temporal,s_precision,s_confidence,s_unrelatedness,s_independence,explanation,config_hash,engine_version) VALUES(?,?,?,?,?,?,?,?,?,?,?)", [row.candidateId, row.components.score, row.components.proximity, row.components.temporal, row.components.precision, row.components.confidence, row.components.unrelatedness, row.components.independence, row.explanation, ctx.configHash, ctx.config.engine_version]); });
  const rejectionCounts = Object.fromEntries([...reasons].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0)); ctx.progress.passFinished(pass, { rows_in: rows.length, rows_out: kept.length, rejected: logs.length, rejections_by_reason: rejectionCounts, elapsed_ms: elapsed(started, ctx.env.now()) });
}
