import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { NodeEnvAdapter } from "../src/adapters/node/env.js";
import { NodeFileSourceAdapter } from "../src/adapters/node/files.js";
import { NodeStorageAdapter } from "../src/adapters/node/storage.js";
import { loadConfig } from "../src/config/config.js";
import type { ArtifactSinkAdapter, PlaceProviderAdapter, PlaceResolution, ProgressReporter } from "../src/core/adapters.js";
import type { EngineContext } from "../src/core/context.js";
import { applyQualifierPenalty, cacheKeyText, loadPlaceNormalizationData, normalizePlaceQuery, radiusForTier, serializeResolution } from "../src/core/place-resolution.js";
import { run as places } from "../src/passes/places.js";
class MemoryArtifacts implements ArtifactSinkAdapter { readonly values=new Map<string,string|Uint8Array>();public async write(name:string,data:string|Uint8Array):Promise<void>{this.values.set(name,data)} }
class SilentProgress implements ProgressReporter { public passStarted(_passName:string):void{} public progress(_passName:string,_completed:number,_total?:number):void{} public passFinished(_passName:string,_report:Readonly<Record<string,unknown>>):void{} public warn(_message:string):void{} }
class FixtureProvider implements PlaceProviderAdapter { public calls=0;readonly #values:ReadonlyMap<string,PlaceResolution>;public constructor(values:ReadonlyMap<string,PlaceResolution>){this.#values=values}public async resolvePlace(rawString:string):Promise<PlaceResolution>{this.calls+=1;return this.#values.get(rawString)??resolution(rawString,"unknown",0,null,null)} }
function resolution(normalized:string,precisionTier:PlaceResolution["precisionTier"],confidence:number,lat:number|null=1,lon:number|null=1):PlaceResolution{return{normalized,lat,lon,precisionTier,admin1:null,admin2:null,country:null,confidence,source:"fixture"}}
async function fixture(t:test.TestContext,provider?:PlaceProviderAdapter):Promise<{storage:NodeStorageAdapter;ctx:EngineContext;artifacts:MemoryArtifacts}>{const directory=await mkdtemp(join(tmpdir(),"samesoil-place-"));t.after(async()=>{await rm(directory,{recursive:true,force:true})});const storage=new NodeStorageAdapter(join(directory,"test.sqlite"));t.after(()=>{storage.close()});storage.applySchema(await readFile(new URL("../src/db/schema.sql",import.meta.url),"utf8"));const env=new NodeEnvAdapter(),loaded=await loadConfig(await readFile(new URL("../config/default.json",import.meta.url),"utf8"),undefined,env),artifacts=new MemoryArtifacts();const ctx:EngineContext={storage,fileSource:new NodeFileSourceAdapter(),artifactSink:artifacts,progress:new SilentProgress(),env,config:loaded.config,configHash:loaded.hash,...(provider===undefined?{}:{placeProvider:provider})};return{storage,ctx,artifacts}}
function seedIndividualEvent(storage:NodeStorageAdapter,placeRaw:string,xref:string):void{const person=storage.run("INSERT INTO individuals(gedcom_xref,is_living) VALUES(?,0)",[xref]);storage.run("INSERT INTO events(subject_type,subject_id,event_type,place_raw) VALUES('individual',?,'RESI',?)",[person.lastInsertRowid,placeRaw])}
test("tier radii come only from config, including explicit unknown behavior",async(t):Promise<void>=>{const{ctx}=await fixture(t);assert.equal(radiusForTier("address",ctx.config.place.radius_km_by_tier),1);assert.equal(radiusForTier("locality",ctx.config.place.radius_km_by_tier),10);assert.equal(radiusForTier("district",ctx.config.place.radius_km_by_tier),50);assert.equal(radiusForTier("region",ctx.config.place.radius_km_by_tier),250);assert.equal(radiusForTier("country",ctx.config.place.radius_km_by_tier),0);assert.equal(radiusForTier("unknown",ctx.config.place.radius_km_by_tier),null)});
test("a warm disk cache makes zero provider calls",async(t):Promise<void>=>{const throwing:PlaceProviderAdapter={async resolvePlace():Promise<PlaceResolution>{throw new Error("provider must not be called")}};const{storage,ctx}=await fixture(t,throwing);seedIndividualEvent(storage,"Denver, CO","@I1@");const env=new NodeEnvAdapter(),hash=await env.sha256(cacheKeyText("Denver, Colorado"));storage.run("INSERT INTO geocode_cache(query_hash,query_text,response_json,fetched_at) VALUES(?,?,?,?)",[hash,"Denver, Colorado",serializeResolution(resolution("Denver, Colorado","locality",0.9,39.7392,-104.9903)),env.now()]);await places(ctx);assert.equal(storage.get<{readonly precision_tier:string}>("SELECT precision_tier FROM places WHERE place_raw = ?",["Denver, CO"])?.precision_tier,"locality")});
test("a corrected place survives a rerun byte-for-byte",async(t):Promise<void>=>{const{storage,ctx}=await fixture(t,{async resolvePlace(rawString:string):Promise<PlaceResolution>{return resolution(rawString,"country",0.1,0,0)}});seedIndividualEvent(storage,"Springfield, IL","@I1@");storage.run(`INSERT INTO places(place_raw,place_normalized,lat,lon,radius_km,precision_tier,admin1,admin2,country,geocode_source,geocode_conf,review_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,'corrected')`,["Springfield, IL","Springfield, Illinois",39.7817,-89.6501,10,"locality","Illinois",null,"United States","human",1]);const before=storage.get<Readonly<Record<string,unknown>>>("SELECT * FROM places WHERE place_raw = ?",["Springfield, IL"]);await places(ctx);const after=storage.get<Readonly<Record<string,unknown>>>("SELECT * FROM places WHERE place_raw = ?",["Springfield, IL"]);assert.deepEqual(after,before)});
test("stripping a qualifier lowers confidence",async(t):Promise<void>=>{const provider=new FixtureProvider(new Map([["Denver, Colorado",resolution("Denver, Colorado","locality",0.9,39.7392,-104.9903)]]));const{storage,ctx}=await fixture(t,provider);seedIndividualEvent(storage,"Denver, CO","@I1@");seedIndividualEvent(storage,"near Denver, CO","@I2@");await places(ctx);const plain=storage.get<{readonly geocode_conf:number}>("SELECT geocode_conf FROM places WHERE place_raw = ?",["Denver, CO"]),qualified=storage.get<{readonly geocode_conf:number}>("SELECT geocode_conf FROM places WHERE place_raw = ?",["near Denver, CO"]);assert.equal(plain?.geocode_conf,0.9);assert.equal(qualified?.geocode_conf,applyQualifierPenalty(0.9,ctx.config.place.min_geocode_conf));assert.ok((qualified?.geocode_conf??1)<(plain?.geocode_conf??0))});
test("ten messy GEDCOM place strings normalize and resolve deterministically",async(t):Promise<void>=>{const values=new Map<string,PlaceResolution>([["Boston, Massachusetts",resolution("Boston, Massachusetts","locality",0.9)],["Denver, Colorado",resolution("Denver, Colorado","locality",0.92)],["St. Louis County, Missouri",resolution("St. Louis County, Missouri","district",0.85)],["Orleans Parish, Louisiana",resolution("Orleans Parish, Louisiana","district",0.82)],["Jefferson County, Kentucky",resolution("Jefferson County, Kentucky","district",0.8)],["Pittsburg, Pennsylvania",resolution("Pittsburg, Pennsylvania","locality",0.62)],["Washington County (historical), Virginia",resolution("Washington County (historical), Virginia","district",0.55)],["New York, New York, USA",resolution("New York, New York, USA","locality",0.9)],["England",resolution("England","country",0.95)]]);const{storage,ctx}=await fixture(t,new FixtureProvider(values));const cases=[["of Boston, MA","Boston, Massachusetts","locality",10,0.54],["near Denver, CO","Denver, Colorado","locality",10,0.552],["probably St. Louis Co., MO","St. Louis County, Missouri","district",50,0.51],["Orleans Parish, LA","Orleans Parish, Louisiana","district",50,0.82],["Jefferson Cnty., KY","Jefferson County, Kentucky","district",50,0.8],["Pittsburg, PA","Pittsburg, Pennsylvania","locality",10,0.62],["Washington County (historical), VA","Washington County (historical), Virginia","district",50,0.55],["New York, NY, USA","New York, New York, USA","locality",10,0.9],["England","England","country",0,0.95],["","","unknown",null,0]] as const;for(const[index,[raw]]of cases.entries())seedIndividualEvent(storage,raw,`@I${index+1}@`);await places(ctx);const data=await loadPlaceNormalizationData(ctx.fileSource,"src/data/us-place-abbreviations.json");for(const[raw,normalized,tier,radius,confidence]of cases){assert.equal(normalizePlaceQuery(raw,data).normalized,normalized);const row=storage.get<{readonly precision_tier:string;readonly radius_km:number|null;readonly geocode_conf:number}>("SELECT precision_tier,radius_km,geocode_conf FROM places WHERE place_raw = ?",[raw]);assert.equal(row?.precision_tier,tier);assert.equal(row?.radius_km,radius);assert.ok(Math.abs((row?.geocode_conf??-1)-confidence)<1e-12)}});
