import type { EnvAdapter } from "../core/adapters.js";
export type PrecisionTier = "address" | "locality" | "district" | "region" | "country"; export type ScoredPrecisionTier = PrecisionTier | "unknown"; export type DatePrecision = "day" | "month" | "year" | "decade" | "range" | "inferred";
export interface PresenceProjection { readonly subject: number; readonly spouse?: number; readonly mother?: number; readonly father?: number; readonly parents?: number }
export interface SamesoilConfig { readonly engine_version: string; readonly date: { readonly abt_years: number; readonly est_years: number; readonly cal_years: number; readonly open_interval_fallback_years: number; readonly pre_1752_widen_days: number }; readonly presence: { readonly point_event_dwell_days: number; readonly transit_event_window_days: number; readonly min_presence_conf: number; readonly projections: Readonly<Record<string, PresenceProjection>> }; readonly place: { readonly radius_km_by_tier: Readonly<Record<PrecisionTier, number>>; readonly min_tier: PrecisionTier; readonly proximity_radius_multiplier: number; readonly min_geocode_conf: number }; readonly kinship: { readonly close_kin_cutoff: number; readonly in_law_cutoff: number; readonly generations_cutoff: number; readonly branch_cutoff: number; readonly bfs_max_depth: number }; readonly scoring: { readonly weights: { readonly proximity: number; readonly temporal: number; readonly precision: number; readonly confidence: number; readonly unrelatedness: number; readonly independence: number }; readonly precision_tier_weights: Readonly<Record<ScoredPrecisionTier, number>>; readonly temporal_precision_weights: Readonly<Record<DatePrecision, number>>; readonly proximity_score_max_km: number; readonly temporal_overlap_full_days: number; readonly temporal_min_overlap_factor: number; readonly temporal_candidate_window_days: number; readonly temporal_gap_full_score_days: number; readonly temporal_gap_min_factor: number; readonly independence_same_record: number; readonly independence_distinct_record: number; readonly score_threshold: number; readonly max_candidates: number; readonly max_candidates_per_locality: number }; readonly privacy: { readonly include_living: boolean; readonly living_cutoff_year: number } }
export interface LoadedConfig { readonly config: SamesoilConfig; readonly hash: string; readonly canonicalJson: string }
type JsonObject = Record<string, unknown>; const isObject = (value: unknown): value is JsonObject => typeof value === "object" && value !== null && !Array.isArray(value);
function merge(defaults: unknown, override: unknown, path: string): unknown { if (override === undefined) return defaults; if (isObject(defaults)) { if (!isObject(override)) throw new Error(`${path}: expected object`); const unknown = Object.keys(override).filter((key) => !(key in defaults)); if (unknown.length > 0) throw new Error(`${path}.${unknown[0]}: unknown key`); return Object.fromEntries(Object.keys(defaults).map((key) => [key, merge(defaults[key], override[key], `${path}.${key}`)])); } return override; }
function requireObject(value: unknown, path: string): JsonObject { if (!isObject(value)) throw new Error(`${path}: expected object`); return value; }
function requireString(value: unknown, path: string): string { if (typeof value !== "string" || value.length === 0) throw new Error(`${path}: expected non-empty string`); return value; }
function requireNumber(value: unknown, path: string): number { if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`${path}: expected finite number`); return value; }
function requireBoolean(value: unknown, path: string): boolean { if (typeof value !== "boolean") throw new Error(`${path}: expected boolean`); return value; }
function numberObject(value: unknown, path: string, keys: readonly string[]): Record<string, number> { const object = requireObject(value, path); return Object.fromEntries(keys.map((key) => [key, requireNumber(object[key], `${path}.${key}`)])); }
function assertRange(value: number, path: string, minimum: number, maximum: number): void { if (value < minimum || value > maximum) throw new Error(`${path}: expected ${minimum}..${maximum}`); }
function assertInteger(value: number, path: string, minimum: number): void { if (!Number.isInteger(value) || value < minimum) throw new Error(`${path}: expected integer >= ${minimum}`); }
function assertNonIncreasing(values: ReadonlyArray<readonly [string, number]>, path: string): void { for (let index = 1; index < values.length; index += 1) { const previous = values[index - 1], current = values[index]; if (previous !== undefined && current !== undefined && current[1] > previous[1]) throw new Error(`${path}.${current[0]}: must not exceed ${path}.${previous[0]}`); } }
function projections(value: unknown, path: string): Readonly<Record<string, PresenceProjection>> { const object = requireObject(value, path), result: Record<string, PresenceProjection> = {}; for (const key of Object.keys(object).sort()) { const row = requireObject(object[key], `${path}.${key}`), allowed = ["subject", "spouse", "mother", "father", "parents"], unknown = Object.keys(row).filter((name) => !allowed.includes(name)); if (unknown.length > 0) throw new Error(`${path}.${key}.${unknown[0]}: unknown key`); const projection: Record<string, number> = { subject: requireNumber(row.subject, `${path}.${key}.subject`) }; assertRange(projection.subject ?? 0, `${path}.${key}.subject`, 0, 1); for (const name of allowed.slice(1)) if (row[name] !== undefined) { const number = requireNumber(row[name], `${path}.${key}.${name}`); assertRange(number, `${path}.${key}.${name}`, 0, 1); projection[name] = number; } result[key] = projection as unknown as PresenceProjection; } return result; }
function validate(value: unknown): SamesoilConfig {
  const root = requireObject(value, "config"), date = numberObject(root.date, "config.date", ["abt_years", "est_years", "cal_years", "open_interval_fallback_years", "pre_1752_widen_days"]), presenceRoot = requireObject(root.presence, "config.presence"), presenceNumbers = numberObject(presenceRoot, "config.presence", ["point_event_dwell_days", "transit_event_window_days", "min_presence_conf"]), place = requireObject(root.place, "config.place"), radii = numberObject(place.radius_km_by_tier, "config.place.radius_km_by_tier", ["address", "locality", "district", "region", "country"]), kinship = numberObject(root.kinship, "config.kinship", ["close_kin_cutoff", "in_law_cutoff", "generations_cutoff", "branch_cutoff", "bfs_max_depth"]), scoring = requireObject(root.scoring, "config.scoring"), weights = numberObject(scoring.weights, "config.scoring.weights", ["proximity", "temporal", "precision", "confidence", "unrelatedness", "independence"]), precisionWeights = numberObject(scoring.precision_tier_weights, "config.scoring.precision_tier_weights", ["address", "locality", "district", "region", "country", "unknown"]), temporalWeights = numberObject(scoring.temporal_precision_weights, "config.scoring.temporal_precision_weights", ["day", "month", "year", "decade", "range", "inferred"]), privacy = requireObject(root.privacy, "config.privacy"), tier = requireString(place.min_tier, "config.place.min_tier");
  if (!["address", "locality", "district", "region", "country"].includes(tier)) throw new Error("config.place.min_tier: invalid precision tier");
  for (const [key, number] of Object.entries(date)) assertInteger(number, `config.date.${key}`, 0);
  assertInteger(presenceNumbers.point_event_dwell_days ?? -1, "config.presence.point_event_dwell_days", 0); assertInteger(presenceNumbers.transit_event_window_days ?? -1, "config.presence.transit_event_window_days", 0); assertRange(presenceNumbers.min_presence_conf ?? -1, "config.presence.min_presence_conf", 0, 1);
  for (const [key, number] of Object.entries(radii)) if (number < 0) throw new Error(`config.place.radius_km_by_tier.${key}: expected >= 0`);
  const proximityRadiusMultiplier = requireNumber(place.proximity_radius_multiplier, "config.place.proximity_radius_multiplier"), minGeocodeConf = requireNumber(place.min_geocode_conf, "config.place.min_geocode_conf"); if (proximityRadiusMultiplier <= 0) throw new Error("config.place.proximity_radius_multiplier: expected > 0"); assertRange(minGeocodeConf, "config.place.min_geocode_conf", 0, 1);
  for (const [key, number] of Object.entries(kinship)) assertInteger(number, `config.kinship.${key}`, 0); const requiredDepth = Math.max(kinship.close_kin_cutoff ?? 0, kinship.in_law_cutoff ?? 0, kinship.branch_cutoff ?? 0, 2 * (kinship.generations_cutoff ?? 0)); if ((kinship.bfs_max_depth ?? 0) < requiredDepth) throw new Error(`config.kinship.bfs_max_depth: must be >= ${requiredDepth}`);
  for (const [key, number] of Object.entries(weights)) assertRange(number, `config.scoring.weights.${key}`, 0, 1); for (const [key, number] of Object.entries(precisionWeights)) assertRange(number, `config.scoring.precision_tier_weights.${key}`, 0, 1); for (const [key, number] of Object.entries(temporalWeights)) assertRange(number, `config.scoring.temporal_precision_weights.${key}`, 0, 1);
  assertNonIncreasing(["address","locality","district","region","country","unknown"].map((key) => [key, precisionWeights[key] ?? 0] as const), "config.scoring.precision_tier_weights"); assertNonIncreasing(["day","month","year","range","decade","inferred"].map((key) => [key, temporalWeights[key] ?? 0] as const), "config.scoring.temporal_precision_weights");
  const proximityScoreMaxKm = requireNumber(scoring.proximity_score_max_km, "config.scoring.proximity_score_max_km"), overlapFull = requireNumber(scoring.temporal_overlap_full_days, "config.scoring.temporal_overlap_full_days"), overlapMin = requireNumber(scoring.temporal_min_overlap_factor, "config.scoring.temporal_min_overlap_factor"), candidateWindow = requireNumber(scoring.temporal_candidate_window_days, "config.scoring.temporal_candidate_window_days"), gapFull = requireNumber(scoring.temporal_gap_full_score_days, "config.scoring.temporal_gap_full_score_days"), gapMin = requireNumber(scoring.temporal_gap_min_factor, "config.scoring.temporal_gap_min_factor"), sameRecord = requireNumber(scoring.independence_same_record, "config.scoring.independence_same_record"), distinctRecord = requireNumber(scoring.independence_distinct_record, "config.scoring.independence_distinct_record"), threshold = requireNumber(scoring.score_threshold, "config.scoring.score_threshold"), maxCandidates = requireNumber(scoring.max_candidates, "config.scoring.max_candidates"), maxPerLocality = requireNumber(scoring.max_candidates_per_locality, "config.scoring.max_candidates_per_locality");
  if (proximityScoreMaxKm <= 0) throw new Error("config.scoring.proximity_score_max_km: expected > 0"); assertInteger(overlapFull, "config.scoring.temporal_overlap_full_days", 0); assertRange(overlapMin, "config.scoring.temporal_min_overlap_factor", 0, 1); assertInteger(candidateWindow, "config.scoring.temporal_candidate_window_days", 1); assertInteger(gapFull, "config.scoring.temporal_gap_full_score_days", 0); if (gapFull > candidateWindow) throw new Error("config.scoring.temporal_gap_full_score_days: must not exceed temporal_candidate_window_days"); assertRange(gapMin, "config.scoring.temporal_gap_min_factor", 0, 1); assertRange(sameRecord, "config.scoring.independence_same_record", 0, 1); assertRange(distinctRecord, "config.scoring.independence_distinct_record", 0, 1); if (sameRecord > distinctRecord) throw new Error("config.scoring.independence_same_record: must not exceed independence_distinct_record"); assertRange(threshold, "config.scoring.score_threshold", 0, 1); assertInteger(maxCandidates, "config.scoring.max_candidates", 1); assertInteger(maxPerLocality, "config.scoring.max_candidates_per_locality", 1);
  return { engine_version: requireString(root.engine_version, "config.engine_version"), date: date as unknown as SamesoilConfig["date"], presence: { ...presenceNumbers, projections: projections(presenceRoot.projections, "config.presence.projections") } as unknown as SamesoilConfig["presence"], place: { radius_km_by_tier: radii as unknown as Readonly<Record<PrecisionTier, number>>, min_tier: tier as PrecisionTier, proximity_radius_multiplier: proximityRadiusMultiplier, min_geocode_conf: minGeocodeConf }, kinship: kinship as unknown as SamesoilConfig["kinship"], scoring: { weights: weights as unknown as SamesoilConfig["scoring"]["weights"], precision_tier_weights: precisionWeights as unknown as SamesoilConfig["scoring"]["precision_tier_weights"], temporal_precision_weights: temporalWeights as unknown as SamesoilConfig["scoring"]["temporal_precision_weights"], proximity_score_max_km: proximityScoreMaxKm, temporal_overlap_full_days: overlapFull, temporal_min_overlap_factor: overlapMin, temporal_candidate_window_days: candidateWindow, temporal_gap_full_score_days: gapFull, temporal_gap_min_factor: gapMin, independence_same_record: sameRecord, independence_distinct_record: distinctRecord, score_threshold: threshold, max_candidates: maxCandidates, max_candidates_per_locality: maxPerLocality }, privacy: { include_living: requireBoolean(privacy.include_living, "config.privacy.include_living"), living_cutoff_year: requireNumber(privacy.living_cutoff_year, "config.privacy.living_cutoff_year") } };
}
function canonicalize(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonicalize).join(",")}]`; if (isObject(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalize(value[key])}`).join(",")}}`; return JSON.stringify(value); }
export async function loadConfig(defaultJson: string, overrideJson: string | undefined, env: EnvAdapter): Promise<LoadedConfig> { let defaults: unknown, override: unknown = undefined; try { defaults = JSON.parse(defaultJson); } catch { throw new Error("config defaults: invalid JSON"); } if (overrideJson !== undefined) { try { override = JSON.parse(overrideJson); } catch { throw new Error("config override: invalid JSON"); } } const config = validate(merge(defaults, override, "config")), canonicalJson = canonicalize(config); return { config, canonicalJson, hash: await env.sha256(canonicalJson) }; }
