import type { SamesoilConfig } from "../config/config.js";

export type DatePrecision = "day" | "month" | "year" | "range" | "inferred";
export interface LifespanBounds { readonly start: string | null; readonly end: string | null }
export interface NormalizedDate { readonly dateStart: string; readonly dateEnd: string; readonly precision: DatePrecision; readonly qualifier: string | null; readonly parseStatus: "ok" | "partial" }
export interface DateNormalizationResult { readonly value: NormalizedDate | null; readonly reason?: string }
type DateConfig = SamesoilConfig["date"];
type BasicDate = { start: string; end: string; precision: "day" | "month" | "year" };
const MONTHS: Readonly<Record<string, number>> = { JAN:1,FEB:2,MAR:3,APR:4,MAY:5,JUN:6,JUL:7,AUG:8,SEP:9,OCT:10,NOV:11,DEC:12 };
const pad=(value:number):string=>String(value).padStart(2,"0");
const iso=(year:number,month:number,day:number):string=>`${String(year).padStart(4,"0")}-${pad(month)}-${pad(day)}`;
function leap(year:number):boolean{return year%4===0&&(year%100!==0||year%400===0)}
function daysInMonth(year:number,month:number):number{return[31,leap(year)?29:28,31,30,31,30,31,31,30,31,30,31][month-1]??0}
function validYear(value:string):number|null{if(!/^\d{1,4}$/.test(value))return null;const year=Number(value);return year>=1?year:null}
function parseBasic(raw:string):BasicDate|null{const text=raw.trim().toUpperCase();let match=/^(\d{1,2})\s+([A-Z]{3})\s+(\d{1,4})$/.exec(text);if(match!==null){const day=Number(match[1]),month=MONTHS[match[2]??""],year=validYear(match[3]??"");if(month===undefined||year===null||day<1||day>daysInMonth(year,month))return null;const date=iso(year,month,day);return{start:date,end:date,precision:"day"}}match=/^([A-Z]{3})\s+(\d{1,4})$/.exec(text);if(match!==null){const month=MONTHS[match[1]??""],year=validYear(match[2]??"");if(month===undefined||year===null)return null;return{start:iso(year,month,1),end:iso(year,month,daysInMonth(year,month)),precision:"month"}}match=/^(\d{1,4})\/(\d{2,4})$/.exec(text);if(match!==null){const first=validYear(match[1]??"");if(first===null)return null;const suffix=match[2]??"",second=suffix.length===2?Number(`${String(first).slice(0,-2)}${suffix}`):validYear(suffix);if(second===null||second!==first+1)return null;return{start:iso(first,1,1),end:iso(second,12,31),precision:"year"}}const year=validYear(text);return year===null?null:{start:iso(year,1,1),end:iso(year,12,31),precision:"year"}}
function ordinal(year:number,month:number,day:number):number{let y=year,m=month;if(m<=2){y-=1;m+=12}const era=Math.floor(y/400),yoe=y-era*400,doy=Math.floor((153*(m-3)+2)/5)+day-1,doe=yoe*365+Math.floor(yoe/4)-Math.floor(yoe/100)+doy;return era*146097+doe}
function civilFromOrdinal(value:number):[number,number,number]{const era=Math.floor(value/146097),doe=value-era*146097,yoe=Math.floor((doe-Math.floor(doe/1460)+Math.floor(doe/36524)-Math.floor(doe/146096))/365);let year=yoe+era*400;const doy=doe-(365*yoe+Math.floor(yoe/4)-Math.floor(yoe/100)),mp=Math.floor((5*doy+2)/153),day=doy-Math.floor((153*mp+2)/5)+1,month=mp+(mp<10?3:-9);year+=month<=2?1:0;return[year,month,day]}
function addDays(value:string,amount:number):string{const parts=value.split("-").map(Number),result=civilFromOrdinal(ordinal(parts[0]??0,parts[1]??0,parts[2]??0)+amount);return iso(...result)}
const yearOf=(value:string):number=>Number(value.slice(0,4));
export function normalizeGedcomDate(raw:string|null|undefined,config:DateConfig,lifespan:LifespanBounds={start:null,end:null}):DateNormalizationResult{if(raw===null||raw===undefined||raw.trim()==="")return{value:null,reason:"empty"};let text=raw.trim().replace(/\s+/g," ").toUpperCase(),calendar:string|null=null;const calendarMatch=/^(@#D[^@]+@)\s*(.*)$/.exec(text);if(calendarMatch!==null){calendar=calendarMatch[1]??null;text=calendarMatch[2]??"";if(calendar!=="@#DGREGORIAN@"&&calendar!=="@#DJULIAN@")return{value:null,reason:`unsupported calendar ${calendar}`}}let match=/^(BET)\s+(.+)\s+AND\s+(.+)$/.exec(text)??/^(FROM)\s+(.+)\s+TO\s+(.+)$/.exec(text);if(match!==null){const start=parseBasic(match[2]??""),end=parseBasic(match[3]??"");if(start===null||end===null||start.start>end.end)return{value:null,reason:"invalid range"};return{value:{dateStart:start.start,dateEnd:end.end,precision:"range",qualifier:`${calendar===null?"":calendar+" "}${match[1]==="BET"?"BET":"FROM TO"}`,parseStatus:calendar==="@#DJULIAN@"?"partial":"ok"}}}match=/^(ABT|CAL|EST)\s+(.+)$/.exec(text);if(match!==null){const basic=parseBasic(match[2]??"");if(basic===null)return{value:null,reason:"invalid qualified date"};const qualifier=match[1]??"",years=qualifier==="ABT"?config.abt_years:qualifier==="CAL"?config.cal_years:config.est_years;return{value:{dateStart:iso(Math.max(1,yearOf(basic.start)-years),1,1),dateEnd:iso(yearOf(basic.end)+years,12,31),precision:"year",qualifier:`${calendar===null?"":calendar+" "}${qualifier}`,parseStatus:calendar==="@#DJULIAN@"?"partial":"ok"}}}match=/^(BEF|AFT)\s+(.+)$/.exec(text);if(match!==null){const basic=parseBasic(match[2]??"");if(basic===null)return{value:null,reason:"invalid open date"};const qualifier=match[1]??"",known=qualifier==="BEF"?lifespan.start:lifespan.end,start=qualifier==="BEF"?(known??iso(Math.max(1,yearOf(basic.start)-config.open_interval_fallback_years),1,1)):addDays(basic.end,1),end=qualifier==="BEF"?addDays(basic.start,-1):(known??iso(yearOf(basic.end)+config.open_interval_fallback_years,12,31));if(start>end)return{value:null,reason:"outside lifespan"};return{value:{dateStart:start,dateEnd:end,precision:known===null?"inferred":"range",qualifier:`${calendar===null?"":calendar+" "}${qualifier}`,parseStatus:calendar==="@#DJULIAN@"?"partial":"ok"}}}const basic=parseBasic(text);if(basic===null)return{value:null,reason:"unrecognized date"};let start=basic.start,end=basic.end;if(calendar===null&&yearOf(start)<1752){start=addDays(start,-config.pre_1752_widen_days);end=addDays(end,config.pre_1752_widen_days)}return{value:{dateStart:start,dateEnd:end,precision:basic.precision,qualifier:calendar,parseStatus:calendar==="@#DJULIAN@"?"partial":"ok"}}}
