export type KinshipEdgeType = "parent" | "child" | "spouse";
export interface KinshipEdgeInput { readonly fromId:number;readonly toId:number;readonly edgeType:KinshipEdgeType;readonly weight:number }
export interface KinshipGraphEdge { readonly toId:number;readonly edgeType:KinshipEdgeType;readonly weight:number }
export interface KinshipGraph { readonly nodeIds:ReadonlyArray<number>;readonly adjacency:ReadonlyMap<number,ReadonlyArray<KinshipGraphEdge>>;readonly biologicalParents:ReadonlyMap<number,ReadonlyArray<number>> }
export interface KinshipOptions { readonly bfsMaxDepth:number;readonly generationsCutoff:number }
export type GraphConnectionKind="blood"|"marriage"|"social"|"family_graph"|"none";
export interface KinshipAnalysis { readonly aId:number;readonly bId:number;readonly bloodDegree:number|null;readonly graphDegree:number|null;readonly mrcaId:number|null;readonly sameBranch:boolean;readonly shortestBloodPathCount:number;readonly hasMultipleBloodPaths:boolean;readonly aGenerationsToMrca:number|null;readonly bGenerationsToMrca:number|null;readonly bestCommonAncestorCount:number;readonly connectionKind:GraphConnectionKind }
interface AncestorInfo{readonly depth:number;readonly pathCount:number}interface Candidate{readonly id:number;readonly aDepth:number;readonly bDepth:number;readonly pathCount:number}interface Connection{readonly degree:number|null;readonly kind:Exclude<GraphConnectionKind,"blood">}
export const KINSHIP_EDGE_WEIGHTS={biological:1,spouse:1,adopted:2,foster:3,sealed:4}as const;const SPOUSE=1,SOCIAL=2,BIO=KINSHIP_EDGE_WEIGHTS.biological;
const safeAdd=(a:number,b:number):number=>a+b>Number.MAX_SAFE_INTEGER?Number.MAX_SAFE_INTEGER:a+b;const safeMultiply=(a:number,b:number):number=>a*b>Number.MAX_SAFE_INTEGER?Number.MAX_SAFE_INTEGER:a*b;const pair=(a:number,b:number):readonly[number,number]=>a<b?[a,b]:[b,a];
function edgeSort(a:KinshipGraphEdge,b:KinshipGraphEdge):number{return a.toId-b.toId||(a.edgeType<b.edgeType?-1:a.edgeType>b.edgeType?1:0)||a.weight-b.weight}
export function buildKinshipGraph(nodeIds:ReadonlyArray<number>,edges:ReadonlyArray<KinshipEdgeInput>):KinshipGraph{const adjacency=new Map<number,KinshipGraphEdge[]>(),parents=new Map<number,number[]>();for(const id of[...new Set(nodeIds)].sort((a,b)=>a-b))adjacency.set(id,[]);for(const edge of edges){if(!adjacency.has(edge.fromId))adjacency.set(edge.fromId,[]);if(!adjacency.has(edge.toId))adjacency.set(edge.toId,[]);adjacency.get(edge.fromId)?.push({toId:edge.toId,edgeType:edge.edgeType,weight:edge.weight});if(edge.edgeType==="parent"&&edge.weight===BIO){const values=parents.get(edge.toId)??[];values.push(edge.fromId);parents.set(edge.toId,values)}}const frozenAdjacency=new Map<number,ReadonlyArray<KinshipGraphEdge>>(),frozenParents=new Map<number,ReadonlyArray<number>>();for(const[id,values]of adjacency)frozenAdjacency.set(id,[...values].sort(edgeSort));for(const[id,values]of parents)frozenParents.set(id,[...new Set(values)].sort((a,b)=>a-b));return{nodeIds:[...adjacency.keys()].sort((a,b)=>a-b),adjacency:frozenAdjacency,biologicalParents:frozenParents}}
function ancestors(graph:KinshipGraph,start:number,max:number):ReadonlyMap<number,AncestorInfo>{const result=new Map<number,AncestorInfo>([[start,{depth:0,pathCount:1}]]);let frontier=new Map<number,number>([[start,1]]);for(let depth=0;depth<max&&frontier.size>0;depth++){const next=new Map<number,number>();for(const[node,count]of[...frontier].sort(([a],[b])=>a-b))for(const parent of graph.biologicalParents.get(node)??[]){const known=result.get(parent),candidate=depth+1;if(known!==undefined&&known.depth<candidate)continue;next.set(parent,safeAdd(next.get(parent)??0,count))}for(const[node,count]of[...next].sort(([a],[b])=>a-b)){const known=result.get(node),candidate=depth+1;if(known===undefined)result.set(node,{depth:candidate,pathCount:count});else if(known.depth===candidate)result.set(node,{depth:known.depth,pathCount:safeAdd(known.pathCount,count)})}frontier=new Map([...next].filter(([node])=>result.get(node)?.depth===depth+1))}return result}
function common(a:ReadonlyMap<number,AncestorInfo>,b:ReadonlyMap<number,AncestorInfo>,max:number):ReadonlyArray<Candidate>{const result:Candidate[]=[];for(const[id,left]of a){const right=b.get(id);if(right===undefined||left.depth+right.depth>max)continue;result.push({id,aDepth:left.depth,bDepth:right.depth,pathCount:safeMultiply(left.pathCount,right.pathCount)})}return result.sort((x,y)=>x.aDepth+x.bDepth-y.aDepth-y.bDepth||Math.max(x.aDepth,x.bDepth)-Math.max(y.aDepth,y.bDepth)||x.id-y.id)}
function connection(graph:KinshipGraph,start:number,target:number,max:number):Connection{if(start===target)return{degree:0,kind:"none"};let frontier=new Map<string,{readonly node:number;readonly mask:number}>([[`${start}:0`,{node:start,mask:0}]]);const visited=new Map<string,number>([[`${start}:0`,0]]);for(let depth=0;depth<max&&frontier.size>0;depth++){const next=new Map<string,{readonly node:number;readonly mask:number}>(),targets=new Set<number>();for(const state of[...frontier.values()].sort((a,b)=>a.node-b.node||a.mask-b.mask))for(const edge of graph.adjacency.get(state.node)??[]){const social=edge.edgeType!=="spouse"&&edge.weight!==BIO,mask=state.mask|(edge.edgeType==="spouse"?SPOUSE:0)|(social?SOCIAL:0),key=`${edge.toId}:${mask}`,candidate=depth+1,known=visited.get(key);if(known!==undefined&&known<=candidate)continue;visited.set(key,candidate);next.set(key,{node:edge.toId,mask});if(edge.toId===target)targets.add(mask)}if(targets.size>0){const masks=[...targets],marriage=masks.every(mask=>(mask&SPOUSE)!==0&&(mask&SOCIAL)===0),social=masks.every(mask=>(mask&SOCIAL)!==0&&(mask&SPOUSE)===0);return{degree:depth+1,kind:marriage?"marriage":social?"social":"family_graph"}}frontier=next}return{degree:null,kind:"none"}}
export function analyzeKinship(graph:KinshipGraph,aId:number,bId:number,options:KinshipOptions):KinshipAnalysis{const[a,b]=pair(aId,bId);if(a===b)return{aId:a,bId:b,bloodDegree:0,graphDegree:0,mrcaId:a,sameBranch:true,shortestBloodPathCount:1,hasMultipleBloodPaths:false,aGenerationsToMrca:0,bGenerationsToMrca:0,bestCommonAncestorCount:1,connectionKind:"blood"};const shared=common(ancestors(graph,a,options.bfsMaxDepth),ancestors(graph,b,options.bfsMaxDepth),options.bfsMaxDepth),blood=shared.length===0?null:shared[0].aDepth+shared[0].bDepth,best=blood===null?[]:shared.filter(item=>item.aDepth+item.bDepth===blood),chosen=best[0],paths=best.reduce((total,item)=>safeAdd(total,item.pathCount),0),graphResult=connection(graph,a,b,options.bfsMaxDepth);return{aId:a,bId:b,bloodDegree:blood,graphDegree:graphResult.degree,mrcaId:chosen?.id??null,sameBranch:shared.some(item=>item.aDepth<=options.generationsCutoff&&item.bDepth<=options.generationsCutoff),shortestBloodPathCount:paths,hasMultipleBloodPaths:paths>1,aGenerationsToMrca:chosen?.aDepth??null,bGenerationsToMrca:chosen?.bDepth??null,bestCommonAncestorCount:best.length,connectionKind:blood===null?graphResult.kind:"blood"}}
function ordinal(value:number):string{const hundred=value%100;if(hundred>=11&&hundred<=13)return`${value}th`;const ten=value%10;return`${value}${ten===1?"st":ten===2?"nd":ten===3?"rd":"th"}`}
export function relationshipSummary(result:KinshipAnalysis):string{if(result.bloodDegree!==null&&result.aGenerationsToMrca!==null&&result.bGenerationsToMrca!==null){const a=result.aGenerationsToMrca,b=result.bGenerationsToMrca;if(a===0||b===0){const generations=Math.max(a,b);return generations===1?"parent and child":generations===2?"grandparent and grandchild":`direct ancestor and descendant, ${generations} generations`}if(a===1&&b===1)return result.bestCommonAncestorCount===1?"half-siblings":"siblings";const degree=Math.min(a,b)-1,removed=Math.abs(a-b),base=`${ordinal(degree)} cousins`;return removed===0?base:`${base} ${removed===1?"once":removed===2?"twice":`${removed} times`} removed`}if(result.graphDegree===null)return"no known relationship";const edges=`${result.graphDegree} ${result.graphDegree===1?"edge":"edges"}`;return result.connectionKind==="marriage"?`connected by marriage, ${edges}`:result.connectionKind==="social"?`connected by social family links, ${edges}`:`connected by family graph, ${edges}`}
export class KinshipResolver{readonly#graph:KinshipGraph;readonly#options:KinshipOptions;readonly#cache=new Map<string,KinshipAnalysis>();public constructor(graph:KinshipGraph,options:KinshipOptions){this.#graph=graph;this.#options=options}public resolve(aId:number,bId:number):KinshipAnalysis{const[a,b]=pair(aId,bId),key=`${a}:${b}`,cached=this.#cache.get(key);if(cached!==undefined)return cached;const result=analyzeKinship(this.#graph,a,b,this.#options);this.#cache.set(key,result);return result}public get cacheSize():number{return this.#cache.size}}
