export type PrecisionTier = "address" | "locality" | "district" | "region" | "country" | "unknown";
export type DatePrecision = "day" | "month" | "year" | "decade" | "range" | "inferred";
export interface ScoreWeights { readonly proximity: number; readonly temporal: number; readonly precision: number; readonly confidence: number; readonly unrelatedness: number; readonly independence: number }
export interface ScoringConfig { readonly weights: ScoreWeights; readonly precision_tier_weights: Readonly<Record<PrecisionTier, number>>; readonly temporal_precision_weights: Readonly<Record<DatePrecision, number>>; readonly proximity_score_max_km: number; readonly temporal_overlap_full_days: number; readonly temporal_min_overlap_factor: number; readonly temporal_candidate_window_days: number; readonly temporal_gap_full_score_days: number; readonly temporal_gap_min_factor: number; readonly independence_same_record: number; readonly independence_distinct_record: number }
export interface ScoreInput { readonly distanceKm: number; readonly combinedRadiusKm: number; readonly proximityMultiplier: number; readonly overlapDays: number; readonly temporalGapDays: number; readonly aDatePrecision: DatePrecision; readonly bDatePrecision: DatePrecision; readonly aTier: PrecisionTier; readonly bTier: PrecisionTier; readonly aPresenceConfidence: number; readonly bPresenceConfidence: number; readonly aGeocodeConfidence: number; readonly bGeocodeConfidence: number; readonly bloodDegree: number | null; readonly branchCutoff: number; readonly sameSourceRecord: boolean }
export interface ScoreComponents { readonly proximity: number; readonly temporal: number; readonly temporalProximity: number; readonly datePrecision: number; readonly precision: number; readonly confidence: number; readonly unrelatedness: number; readonly independence: number; readonly score: number }
const clamp = (value: number): number => Math.max(0, Math.min(1, value));
export function proximityScore(distanceKm: number, maximumDistanceKm: number, multiplier: number): number { const limit = maximumDistanceKm * multiplier; if (limit <= 0 || distanceKm >= limit) return distanceKm === 0 && limit === 0 ? 1 : 0; const ratio = clamp(distanceKm / limit); return (1 + Math.cos(Math.PI * ratio)) / 2; }
export function precisionScore(a: PrecisionTier, b: PrecisionTier, weights: Readonly<Record<PrecisionTier, number>>): number { return clamp(Math.min(weights[a], weights[b])); }
export function datePrecisionScore(a: DatePrecision, b: DatePrecision, weights: Readonly<Record<DatePrecision, number>>): number { return clamp(Math.sqrt(clamp(weights[a]) * clamp(weights[b]))); }
export function temporalProximityScore(overlapDays: number, gapDays: number, config: ScoringConfig): number { if (overlapDays > 0) return 1; if (gapDays <= 0 || gapDays > config.temporal_candidate_window_days) return 0; if (gapDays <= config.temporal_gap_full_score_days) return 1; const span = config.temporal_candidate_window_days - config.temporal_gap_full_score_days; if (span <= 0) return config.temporal_gap_min_factor; const progress = clamp((gapDays - config.temporal_gap_full_score_days) / span); return clamp(1 - (1 - config.temporal_gap_min_factor) * progress); }
export function temporalScore(overlapDays: number, gapDays: number, a: DatePrecision, b: DatePrecision, config: ScoringConfig): number { return clamp(temporalProximityScore(overlapDays, gapDays, config) * datePrecisionScore(a, b, config.temporal_precision_weights)); }
export function confidenceScore(aPresence: number, bPresence: number, aGeocode: number, bGeocode: number): number { return clamp(Math.sqrt(clamp(aPresence) * clamp(bPresence)) * Math.sqrt(clamp(aGeocode) * clamp(bGeocode))); }
export function unrelatednessScore(bloodDegree: number | null, branchCutoff: number): number { return bloodDegree === null ? 1 : branchCutoff <= 0 ? 0 : clamp(bloodDegree / branchCutoff); }
export function independenceScore(sameSourceRecord: boolean, config: ScoringConfig): number { return clamp(sameSourceRecord ? config.independence_same_record : config.independence_distinct_record); }
export function scoreCandidate(input: ScoreInput, config: ScoringConfig): ScoreComponents { const proximity = proximityScore(input.distanceKm, config.proximity_score_max_km, 1), temporalProximity = temporalProximityScore(input.overlapDays, input.temporalGapDays, config), datePrecision = datePrecisionScore(input.aDatePrecision, input.bDatePrecision, config.temporal_precision_weights), temporal = clamp(temporalProximity * datePrecision), precision = precisionScore(input.aTier, input.bTier, config.precision_tier_weights), confidence = confidenceScore(input.aPresenceConfidence, input.bPresenceConfidence, input.aGeocodeConfidence, input.bGeocodeConfidence), unrelatedness = unrelatednessScore(input.bloodDegree, input.branchCutoff), independence = independenceScore(input.sameSourceRecord, config), score = clamp(config.weights.proximity * proximity * config.weights.temporal * temporal * config.weights.precision * precision * config.weights.confidence * confidence * config.weights.unrelatedness * unrelatedness * config.weights.independence * independence); return { proximity, temporal, temporalProximity, datePrecision, precision, confidence, unrelatedness, independence, score }; }
export interface SuppressionInput { readonly sameIndividual: boolean; readonly living: boolean; readonly duplicateIdentity: boolean; readonly nonOverlappingLifespans: boolean; readonly inferredOpenDate: boolean; readonly directSpouse: boolean; readonly sameHousehold: boolean; readonly bloodDegree: number | null; readonly graphDegree: number | null; readonly sharedMrcaWithinCutoff: boolean; readonly sameBranch: boolean; readonly branchDegree: number | null; readonly coarsePlace: boolean; readonly lowConfidence: boolean }
export interface SuppressionConfig { readonly closeKinCutoff: number; readonly inLawCutoff: number; readonly branchCutoff: number; readonly includeLiving: boolean }
export type SuppressionReason = "same_individual" | "living" | "duplicate_identity" | "nonoverlapping_lifespans" | "inferred_open_date" | "spouse" | "same_household" | "close_kin" | "in_law" | "recent_mrca" | "same_branch" | "coarse_place" | "low_conf";
export function firstSuppression(input: SuppressionInput, config: SuppressionConfig): SuppressionReason | null { if (input.sameIndividual) return "same_individual"; if (input.living && !config.includeLiving) return "living"; if (input.duplicateIdentity) return "duplicate_identity"; if (input.nonOverlappingLifespans) return "nonoverlapping_lifespans"; if (input.inferredOpenDate) return "inferred_open_date"; if (input.directSpouse) return "spouse"; if (input.sameHousehold) return "same_household"; if (input.bloodDegree !== null && input.bloodDegree <= config.closeKinCutoff) return "close_kin"; if (input.graphDegree !== null && input.graphDegree <= config.inLawCutoff) return "in_law"; if (input.sharedMrcaWithinCutoff) return "recent_mrca"; if (input.sameBranch && input.branchDegree !== null && input.branchDegree < config.branchCutoff) return "same_branch"; if (input.coarsePlace) return "coarse_place"; if (input.lowConfidence) return "low_conf"; return null; }
